-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 2018  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Intel Program License
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details.


-- Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
-- Created on Tue Nov 27 19:59:46 2018

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;


--  Entity Declaration

ENTITY counter IS
-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
PORT
(
clear : IN STD_LOGIC;									--clear counter input
clk : IN STD_LOGIC;										--clock input
nrst: IN STD_LOGIC;										--async reset
q : OUT STD_LOGIC_vector(7 DOWNTO 0)				--counter vector output
);
-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END counter;


--  Architecture Body

ARCHITECTURE counter_architecture OF counter IS
signal count : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00000000";

BEGIN
q <= count;

process(clk, nrst)
	begin
		IF nrst = '1' THEN
			IF(rising_edge(clk)) and (clear = '0') THEN			--if NRST, rising edge clk and not clearing, count +1
				count <= count + 1;
			ELSIF (rising_edge(clk)) and (clear = '1') THEN		--else if NRST, rising edge clk and clear, count <= "0000000"
				count <= "00000000";
			END IF;
		ELSE
			count <= "00000000";			--if /NRST, clear counter output, no counter operation
		END IF;
			
 	end process;

END counter_architecture;
